### ISSUE TITLE
Mod not showing up

### ISSUE THREAD

**Issue by RezTheChez** [ArilisGit/DupeMod#2]
Whenever I launch 1.8.9 with forge and the mod in the mod folder,
![image](https://user-images.githubusercontent.com/103398512/162851398-588ce7e3-9b7f-41af-9525-5be6427b230c.png)
it does not show the mod in the loaded mods section. 
![image](https://user-images.githubusercontent.com/103398512/162851656-cc293bf0-f1a5-4ae1-96a3-15ac30956dc3.png)
![image](https://user-images.githubusercontent.com/103398512/162851678-d5706355-d6f1-471b-a7f0-4a81c71ce21e.png)

**Comment by ArilisGit** [comment]
The mod was broken, I have just updated it for you!
